cc_binary(
    name= 'split_file',
    defs = [],
    srcs=[
        'SplitFile.cpp',
       ],
    deps=[
        '//CommonTools:CommonTools',
    ],
    #extra_cppflags=['-fopenmp'],
    #extra_linkflags=['-fopenmp'],
)
